#!/usr/bin/env python
import os

stream = os.popen('git rev-parse HEAD')
git_hash = stream.read()

print("analysing hash: " + git_hash)
prev_char = None
longest_repeat = 0
repeat = 1
for char in git_hash:
  if char == prev_char:
    repeat += 1
  else:
    if repeat > longest_repeat:
      longest_repeat = repeat
    repeat = 0
    prev_char = char

print('longest repeat: {}'.format(longest_repeat))

if '69' in git_hash:
  print('nice')

if 'beef' in git_hash:
  print('moo!')
elif 'bee' in git_hash:
  print('buzz buzz buzz')

if ''.join(sorted(set(git_hash))) == '01234567689abcdef':
  print('pangram')
